repo: 'events-calendar'
canvasCourse: 'web-dev-2'

inherit:
  - naming-restrict-live
  - git-2
  - html
  - css
  - google-fonts
  - modulifier
  - typografier
  - css-order-modules-type-main
  - modulifier-list-group

html:
  - path: 'index.html'
    outline: false
    has:
      - ['link[href*="Merriweather:400,400i,700"]', 'The Google Font, `Merriweather` (regular, italic & bold) is missing']
      - 'table'
      - 'thead'
      - 'tbody'
      - 'caption'
      - 'th'
      - 'tr'
      - 'td'
      - 'th[scope]'
      - '[colspan]'
    search:
      - 'November, 1963'
      - 'Sun'
      - 'Mon'
      - 'Tue'
      - 'Wed'
      - 'Thu'
      - 'Fri'
      - 'Sat'
      - 'India launched its first rocket'
      - 'Surtsey Island created'
      - 'Doctor Who premiered'

css:
  - path: 'css/main.css'
    has:
      - ['html', 'font-family', 'Merriweather, serif']
    search:
      - 'background-color'
      - 'border'
      - 'color'
      - 'border-radius'
      - '#ccc'
      - '#f2f2f2'
      - '#666'
      - '#333'
      - '#d1e0bf'
      - '#6b7e54'
      - '#51603f'
      - '#d2d6f0'
      - '#1d38da'
      - '#38448e'
      - '#f2bcbc'
      - '#b92828'
      - '#991919'
    search_not:
      - 'padding'
      - 'margin'
      - 'font-size'
      - 'font-weight'
      - 'text-align'
      - 'list-style-type'

screenshots:
  - path: 'index.html'
    sizes: [1434]
